config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'home#index'

  resources :stories

  resources :users

  resources :prompts

  resources :categories
 
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :prompts
	has_many :stories
	has_many :stories, :through => :prompts
end

app/models/group.rb
class Group < ActiveRecord::Base
	belongs_to :user_group
end

app/models/prompt.rb
class Prompt < ActiveRecord::Base
	has_many :stories
	belongs_to :category
end

app/models/story.rb
class Story < ActiveRecord::Base
	belongs_to :user
	belongs_to :prompt

	mount_uploader :photo, PhotoUploader

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   has_many :stories
end

app/models/user_group.rb
class UserGroup < ActiveRecord::Base
	has_many :users
	has_many :groups
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :set_prompts
  before_action :set_categories
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(user)
 	  new_story_path
  end
   
  
  def set_categories
    @categories = Category.all
  end 


  def set_prompts
    @prompts = Prompt.all
  end 
   

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
  	@category = Category.all
  end

  def show
  	@category = Category.find(params[:id])

  	@stories = @category.stories
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/prompts_controller.rb
class PromptsController < ApplicationController
	def index
		@prompt = Prompt.all
	end

	def show
		@prompt = Prompt.find(params[:id])
		@stories = @prompt.stories
	end

	def new
		@prompt = Prompt.new
	end

	def create
		@prompt = Prompt.new(prompt_params)
		if @prompt.save
			redirect_to stories_path
		else 
			render :new
		end
	end

	def prompt_params
		params.require(:prompt).permit(:name, :category_id)
	end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
	before_action :authenticate_user!

	def index
		@prompt = Prompt.all
		@stories = Story.all.order('created_at DESC')
		@user = User.all
	end

	def new
		@prompt = Prompt.all.order('RANDOM()').first
		@story = Story.new(prompt: @prompt)
	end

	def create
		@story = Story.new(story_params)
		@story.user = current_user

		if @story.save
			redirect_to stories_path
		else
			render :new
		end
	end

 	def edit
		@story = current_user.stories.find(params[:id])
		@photo = @story.photo
 	end

 	def update
    @story = Story.find(params[:id])
    if @story.update_attributes(story_params)
   		redirect_to stories_path
 		else 
  		render :edit
 		end
 	end

 	def show
 	 @story = Story.find(params[:id])
 	 @prompt = @story.prompt.name
 	end

 	def destroy
    @story = Story.find(params[:id])
    @story.delete
    redirect_to stories_path
  end


	def story_params
		params.require(:story).permit(:body, :prompt_id, :photo)
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		@user = User.find(params[:id])
		@stories = @user.stories.order('created_at DESC')
	end
end

app/views/categories/index.html.erb
<h1>Prompt Categories</h1>

<br>

<%= link_to @category.each do |c| %>
<%= c.name %><br>
<% end %>

app/views/categories/show.html.erb
<h1><%= "#{@category.name} Stories" %></h1> <br><br>
<% @stories.each do |s| %><br>
<h4><%= s.prompt.name.capitalize %><br></h4>
<h8><%= link_to s.user.email, user_path(s.user) %></h8><br>
<br><%= image_tag s.photo, size: '100x100' %><br>
<%= s.body %><hr>
<% end %>

app/views/home/index.html.erb
<div class = "center jumbotron">
    <h1>Welcome to Storiez!</h1><br>
    
    <h4>A place to read, share and store memories from friends and family</h4>

    <br>

    <h5><%= link_to 'Sign Up', new_user_registration_path, class: "btn btn-lg btn-default" %><h5>  <h5><%= link_to 'Log in', new_user_session_path, class: "btn btn-lg btn-default"%></h5>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Storiez" %></title>
    <%= csrf_meta_tags %>


    <%= stylesheet_link_tag "application", :media => "all" %>

    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">

      <div class="container">
      <% if user_signed_in? %>
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" ><%= link_to "Storiez", stories_path%></a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><% if user_signed_in? %>
                  <%= link_to "My Stories", user_path(current_user) %>
                <% end %>
            <li><%= link_to "Create Prompt", new_prompt_path %></li>
            <li id="dropdown" class="dropdown prompt">Filter by prompt</li>
              <ul class="fallback prompt dropdown-menu">
               <% @prompts.each do |prompt| %>
                 <li><%= link_to prompt.name, prompt_path(prompt)%></li>
               <% end %>
             </ul>
             <li id="dropdown" class="dropdown  category">Filter by Category</li>
              <ul class="fallback category dropdown-menu">
               <% @categories.each do |category| %>
                 <li><%= link_to category.name, category_path(category)%></li>
               <% end %>
             </ul>
         
              <li><% if user_signed_in? %>
             <%= link_to "Sign Out", destroy_user_session_path, :method => :delete  %></li>
             <%end%>
                </ul>
        </div>
      </div>
      <%end%>
    </div>

  
    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <% unless current_page?('/') %>
            <p class="notice"><%= notice %></p>
            <p class="alert"><%= alert %></p>  
          <% end %>
          <%= yield %>
        </div>
      </div><!--/row-->
<!-- 
      <footer>
        <p>&copy; Company 2015</p>
      </footer>
 -->
    </div> <!-- /container -->

  </body>
</html>

app/views/prompts/new.html.erb
<h2> What is a story you would love to hear about? </h2> <br>

<h5>*Hint* Think of funny or significant memories from your own life that you don't know about your friends and family.  No punctuation needed. All prompts will be pre-empted by "Write about.." so phrase accordingly.</h5>

<%= simple_form_for @prompt, html: { class: 'form-horizontal' } do |form| %><br>
	 <%= form.input :name, label: "New prompt:", as: :text %><br>
	 <%= form.association :category, label: "Select a category", label_method: :name %><br>
	 <%= form.button :submit, class: 'btn btn-default' %>
	  <% end %>

app/views/prompts/show.html.erb
<h1><%= "All stories about #{@prompt.name}"%></h1><br>

<% @stories.each do |story| %><br>
<h5><%= story.user.email%><br></h5>
<h6><%= story.created_at.strftime("%d %b. %Y") %> </h6><br>
<%= story.body.first(400)%><br><br>
<%= image_tag story.photo, size: '100x100'%><br><hr>

<% end %>

<h4><%=link_to 'Write a story', new_story_path(:id), class: "btn btn-lg btn-default"%><br></h4>

app/views/stories/edit.html.erb
<br><br><br><div class = "row">
	<div class="col-md-7">

<%= simple_form_for @story, html: {class: 'form-horizontal'} do |form| %>
	<%= form.input :body, label: 'Edit Text'%> <br>
	 <%= form.input :photo, label: "Change photo:"%><br>
	 <%= form.submit 'Update', class: 'btn btn-info' %>
	<% end %><br>
	 <%= button_to 'Delete Story', story_path(@story), method: :delete,class: 'btn btn-danger' %>
	</div><br>
	

	<div class="col-md-5">
    <%= image_tag @story.photo, size: '300x300' %>
  </div>

</div>

app/views/stories/index.html.erb
<h1>aLL tHe sToRieZ!</h1><br>


<h4><%=link_to 'Write a new Story', new_story_path(Prompt.first), class: "btn btn-lg btn-default"%><br></h4>
<hr>

<% @stories.each do |story| %>
	<h4><%= link_to story.prompt.name.capitalize, story_path(story) %></h4> 
	<%= link_to story.user.email, user_path(story.user)%>
	<h6><%= story.created_at.strftime("%d %b. %Y") %> </h6><br>
	<%= story.body.first(400) %>   <%= link_to "(more)", story_path(story) %><br><br>
	<%= image_tag story.photo, size: '100x100' %>
	<hr>
<% end %>

app/views/stories/new.html.erb
<br>
<br>
<br>


<h2><%= "Write about #{@prompt.name}"%></h2>
<h9><small><%= "Use the above prompt to guide your story. Be descriptive - the longer the better! You can add a photo to go along with your story."%></small></h9>

<div class="row">
<div class = "col-md-8">
	<div class="col-md-9">

<%= simple_form_for @story, html: { class: 'form-horizontal'} do |form| %><br>
	 <%= form.input :body, label: "Your story:", as: :text %><br>
	 <%= form.input :prompt_id, as: :hidden %><br>
	 <%= form.input :photo, label: "Include a photo:"%><br>
	 <%= form.submit 'Post', class: 'btn btn-primary' %>
<% end %>
</div>
</div>
</div>

app/views/stories/show.html.erb
<h3><%= "#{@prompt.capitalize}"%></h3><hr>

<h5><%= @story.user.email %></h5>
<h6><%= @story.created_at.strftime("%d %b. %Y") %> </h6><br>
<h7><%= @story.body %></h7><br>
<br>
<%= image_tag @story.photo, size: '300x300' %>
<hr>

app/views/users/show.html.erb
<h3><%="#{@user.email}'s stories"%></h3><br>
<% @stories.each do |s| %>
<h4><%= s.prompt.name.capitalize%></h4>
<br><%= image_tag s.photo, size: '100x100' %><br><br>
<%= s.body %><br><hr>
<% if s.user == current_user %>
	<%= link_to "Edit", edit_story_path(s) %>
	<% end %>
<% end %>